/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: (typeof import('./src/components/ErrorPage/403.vue'))['default']
    404: (typeof import('./src/components/ErrorPage/404.vue'))['default']
    500: (typeof import('./src/components/ErrorPage/500.vue'))['default']
    copy: (typeof import('./src/components/icons/IconThemeLight copy.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElFooter: (typeof import('element-plus/es'))['ElFooter']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker']
    IconLanguages: (typeof import('./src/components/icons/IconLanguages.vue'))['default']
    IconOutFullScreen: (typeof import('./src/components/icons/IconOutFullScreen.vue'))['default']
    IconRef: (typeof import('./src/components/icons/IconRef.vue'))['default']
    IconRefresh: (typeof import('./src/components/icons/IconRefresh.vue'))['default']
    IconSize: (typeof import('./src/components/icons/IconSize.vue'))['default']
    IconTheme: (typeof import('./src/components/icons/IconTheme.vue'))['default']
    IconThemeDark: (typeof import('./src/components/icons/IconThemeDark.vue'))['default']
    IconThemedrak: (typeof import('./src/components/icons/IconThemedrak.vue'))['default']
    IconThemeDrak: (typeof import('./src/components/icons/IconThemeDrak.vue'))['default']
    IconThemeLight: (typeof import('./src/components/icons/IconThemeLight.vue'))['default']
    IconUser: (typeof import('./src/components/icons/IconUser.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    YoDropdown: (typeof import('./src/components/Dropdown/yoDropdown.vue'))['default']
  }
}
