/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: (typeof import('./src/components/ErrorPage/403.vue'))['default']
    404: (typeof import('./src/components/ErrorPage/404.vue'))['default']
    500: (typeof import('./src/components/ErrorPage/500.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElColorPicker: (typeof import('element-plus/es'))['ElColorPicker']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElFooter: (typeof import('element-plus/es'))['ElFooter']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker']
    IconClassicallayout: (typeof import('./src/components/icons/IconClassicallayout.vue'))['default']
    IconColumnarlayout: (typeof import('./src/components/icons/IconColumnarlayout.vue'))['default']
    IconLanguages: (typeof import('./src/components/icons/IconLanguages.vue'))['default']
    IconOutFullScreen: (typeof import('./src/components/icons/IconOutFullScreen.vue'))['default']
    IconOutSide: (typeof import('./src/components/icons/IconOutSide.vue'))['default']
    IconRefresh: (typeof import('./src/components/icons/IconRefresh.vue'))['default']
    IconSize: (typeof import('./src/components/icons/IconSize.vue'))['default']
    IconThemeDark: (typeof import('./src/components/icons/IconThemeDark.vue'))['default']
    IconThemeLight: (typeof import('./src/components/icons/IconThemeLight.vue'))['default']
    IconUser: (typeof import('./src/components/icons/IconUser.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    YoDropdown: (typeof import('./src/components/Dropdown/yoDropdown.vue'))['default']
    YoEditTheme: (typeof import('./src/components/EditTheme/YoEditTheme.vue'))['default']
  }
}
